/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-09-11 16:33:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import student.Student;

public final class FormStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("student.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"ServletStudent\" method=\"post\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>First name:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentFName\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Last name:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentLName\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Date of birth:</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"studentDOB\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Email:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentEmail\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Phone:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentPhone\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Address:</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"radio\" name=\"gender\" id=\"male\" value=\"Male\">Male\r\n");
      out.write("					<input type=\"radio\" name=\"gender\" id=\"female\" value=\"Female\">Female\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Address:</td>\r\n");
      out.write("				<td><textarea name=\"studentAddress\" rows=\"4\" cols=\"50\"></textarea></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>City:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentCity\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Pin code:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentPin\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>State:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentState\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Country:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"studentCountry\" value=\"India\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Hobbies:</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					Drawing\r\n");
      out.write("					<input type=\"checkbox\" name=\"studentHobbies\" value=\"Reading\">\r\n");
      out.write("					Singing\r\n");
      out.write("					<input type=\"checkbox\" name=\"studentHobbies\" value=\"Writing\">\r\n");
      out.write("					Dancing\r\n");
      out.write("					<input type=\"checkbox\" name=\"studentHobbies\" value=\"Playing\">\r\n");
      out.write("					Sketching\r\n");
      out.write("					<input type=\"checkbox\" name=\"studentHobbies\" value=\"Playing\">\r\n");
      out.write("					Others\r\n");
      out.write("					<input type=\"checkbox\" name=\"studentHobbies\" value=\"Playing\">\r\n");
      out.write("					<input type=\"text\" name=\"studentHobbies\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Qualification:</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<table>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>SL.No.Examination</td>\r\n");
      out.write("							<td>Board</td>\r\n");
      out.write("							<td>Percentage</td>\r\n");
      out.write("							<td>Year of Passing</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>1.  Class X</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentBoard1\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentPercentage1\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentYear1\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>2.  Class XII</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentBoard2\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentPercentage2\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentYear2\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>3.  Graduation</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentBoard3\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentPercentage3\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentYear3\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>4.  Post Graduation</td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentBoard4\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentPercentage4\"></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"studentYear4\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td></td>\r\n");
      out.write("							<td>(10 char max)</td>\r\n");
      out.write("							<td>(upto 2 decimal)</td>\r\n");
      out.write("							<td></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Course Applied for</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					BCA\r\n");
      out.write("					<input type=\"radio\" name=\"studentCourse\" value=\"BCA\">\r\n");
      out.write("					B.Com\r\n");
      out.write("					<input type=\"radio\" name=\"studentCourse\" value=\"B.Com\">\r\n");
      out.write("					B.Sc\r\n");
      out.write("					<input type=\"radio\" name=\"studentCourse\" value=\"B.Sc\">\r\n");
      out.write("					A\r\n");
      out.write("					<input type=\"radio\" name=\"studentCourse\" value=\"A\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"submit\" value=\"Submit\"></td>\r\n");
      out.write("				<td><input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
